name: hackernews-monthly-top

on:
  schedule:
  - cron: "1 0 1 * *"

jobs:
  fetch-top-posts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm install --only=prod
      working-directory: .
    - name: fetch
      run: node index.js
      working-directory: .
