name: hackernews-monthly-top

on:
  workflow_dispatch:
  schedule:
  - cron: "1 0 1 * *"

jobs:
  fetch-top-posts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0 # To get all tags
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm install --only=prod
      working-directory: .
    - name: fetch
      run: node index.js
      working-directory: .
      env:
        clientSecret: ${{ secrets.clientSecret }}
        privateKey: ${{ secrets.privateKey }}
    - uses: stefanzweifel/git-auto-commit-action@v4
        
